POST http://localhost:3005/auth/register
Content-Type: application/json

{
    "email": "princewilljeremiah83@gmail.com",
    "username": "Jay'sCode",
    "password": "drive344@#"
}

###
POST http://localhost:3005/auth/login
Content-Type: application/json

{
     "email": "princewilljeremiah83@gmail.com",
     "password": "drive344@#"
}